SELECT distinct
 LL_ACCOUNT_NO,
 LL_EXTERNAL_ID,
 tmp.ACCOUNT_NUMBER as GPON_ACCOUNT_NO,
 tmp.GPON_NUMBER as GPON_PHONE_NO,
 G_FIRST_SO_ACTIVE_DT AS GPON_FIRST_SO_ACTIVE_DT
FROM atni_dev.gtt_reporting.tmp_dsl_report05 tmp

WHERE 
 (G_INACTIVE_DATE IS NULL AND DSL_ACCOUNT_NO IS NOT NULL AND DSL_INACTIVE_DATE IS NULL
 AND data_bridge_status = 'ENABLED'
 AND voice_bridge_status = 'ENABLED'
 AND GPON_LL_NAME_MATCH >= 20 
 AND GPON_LL_ADDRESS_MATCH >= 20
 AND GPON_DSL_NAME_MATCH >= 20 
 AND GPON_DSL_ADDRESS_MATCH >= 20
 AND upper(DSL_DISCONNECT) != 'DO NOT TERMINATE'
 AND G_FIRST_SO_ACTIVE_DT IS NOT NULL
 AND G_RESIDENTIAL_SO > 0
 AND upper(TRANSFER_HOME_NUMBER) = 'YES'
 )

 OR (G_INACTIVE_DATE IS NULL AND LL_ACCOUNT_NO IS NOT NULL AND LL_INACTIVE_DATE IS NULL

 AND data_bridge_status = 'ENABLED'
 AND voice_bridge_status = 'ENABLED'
 AND GPON_LL_NAME_MATCH >= 20 
 AND GPON_LL_ADDRESS_MATCH >= 20
 AND GPON_DSL_NAME_MATCH >= 20 
 AND GPON_DSL_ADDRESS_MATCH >= 20
 AND upper(DSL_DISCONNECT) != 'DO NOT TERMINATE'
 AND DSL_INACTIVE_DATE IS NULL
 AND G_FIRST_SO_ACTIVE_DT IS NOT NULL
 AND G_RESIDENTIAL_SO > 0
 AND upper(TRANSFER_HOME_NUMBER) = 'YES'
)